In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [19]:
df = pd.read_csv("../data/cleaned/cleaned_top40.csv")

In [20]:
df.head()

,Personality,You are not too interested in discussing various interpretations and analyses of creative works.,You are definitely not an artistic type of person.,Your mood can change very quickly.,You usually prefer just doing what you feel like at any given moment instead of planning a particular daily routine.,You tend to avoid drawing attention to yourself.,You often have a hard time understanding other peoples feelings.,You often make a backup plan for a backup plan.,You are prone to worrying that things will take a turn for the worse.,"In your social circle, you are often the one who contacts your friends and initiates activities.",...,You are still bothered by mistakes that you made a long time ago.,You feel comfortable just walking up to someone you find interesting and striking up a conversation.,"After a long and exhausting week, a lively social event is just what you need.",You prefer to completely finish one project before starting another.,You enjoy going to art museums.,"You have always been fascinated by the question of what, if anything, happens after death.",Is_Extrovert,Is_Sensor,Is_Thinker,Is_Judger
0,ENFP,1,0,0,0,0,-1,0,0,1,...,-1,0,-1,1,0,-1,1,0,0,0
1,ISFP,0,2,-2,1,-2,2,-3,3,-1,...,2,-2,-1,-2,1,1,0,1,0,0
2,INFJ,1,1,-1,0,-1,0,0,0,-2,...,-3,0,0,0,0,-1,0,0,0,1
3,ISTP,-1,-1,0,1,2,3,-1,1,0,...,0,2,0,-2,0,1,0,1,1,0
4,ENFJ,-1,1,-1,0,2,-1,0,2,3,...,-2,0,0,-2,-2,2,1,0,0,1

In [21]:
# Define features and target variable
personalities = ["Is_Extrovert", "Is_Sensor", "Is_Thinker", "Is_Judger"]

X = df.drop(["Personality"] + personalities, axis=1)
y = df[personalities]

In [22]:
X.head()

,You are not too interested in discussing various interpretations and analyses of creative works.,You are definitely not an artistic type of person.,Your mood can change very quickly.,You usually prefer just doing what you feel like at any given moment instead of planning a particular daily routine.,You tend to avoid drawing attention to yourself.,You often have a hard time understanding other peoples feelings.,You often make a backup plan for a backup plan.,You are prone to worrying that things will take a turn for the worse.,"In your social circle, you are often the one who contacts your friends and initiates activities.",You find it easy to empathize with a person whose experiences are very different from yours.,...,You are more inclined to follow your head than your heart.,You enjoy watching people argue.,Your personal work style is closer to spontaneous bursts of energy than organized and consistent efforts.,You enjoy participating in group activities.,You are still bothered by mistakes that you made a long time ago.,You feel comfortable just walking up to someone you find interesting and striking up a conversation.,"After a long and exhausting week, a lively social event is just what you need.",You prefer to completely finish one project before starting another.,You enjoy going to art museums.,"You have always been fascinated by the question of what, if anything, happens after death."
0,1,0,0,0,0,-1,0,0,1,0,...,1,0,0,-1,-1,0,-1,1,0,-1
1,0,2,-2,1,-2,2,-3,3,-1,0,...,-2,1,1,-2,2,-2,-1,-2,1,1
2,1,1,-1,0,-1,0,0,0,-2,0,...,-1,2,-1,2,-3,0,0,0,0,-1
3,-1,-1,0,1,2,3,-1,1,0,-1,...,-1,0,-1,-2,0,2,0,-2,0,1
4,-1,1,-1,0,2,-1,0,2,3,-1,...,-1,-1,-1,-2,-2,0,0,-2,-2,2

In [23]:
y.head()

   Is_Extrovert  Is_Sensor  Is_Thinker  Is_Judger
0             1          0           0          0
1             0          1           0          0
2             0          0           0          1
3             0          1           1          0
4             1          0           0          1

In [24]:
# Split the data into training and testing sets
x_train , x_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(47999, 40)
(47999, 4)
(12000, 40)
(12000, 4)